### PR TITLE
Fix visual bugs

### LINKED ISSUE #80: Fix suggestion bugs for Autocomplete feature

### LINKED ISSUE #104: [Autocomplete] Wrong command format
Wrong format for AddCommand
image

Wrong format for EditCommand
image

### PR DESCRIPTION
**Pull request by saajidshaik02**
Fixes #80 
Fixes #104

### CODE REVIEW

File: src/main/java/seedu/address/ui/CommandBox.java [hunk 1]
```diff
@@ -36,7 +36,9 @@ public class CommandBox extends UiPart<Region> {
     private Label suggestionLabel; // For greyed-out suggestion -> refer to fxml file
 
     static {
-        commandSyntaxMap.put("add", "add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS edu/EDUCATION tele/TELEGRAM_HANDLE");
+        commandSyntaxMap.put("add", "add n/NAME p/PHONE e/EMAIL a/ADDRESS ecname/EMERGENCY CONTACT NAME "
+                + "ecphone/EMERGENCY CONTACT PHONE ecrs/EMERGENCY CONTACT RELATIONSHIP "
+                + "dname/DOCTOR NAME dphone/DOCTOR PHONE demail/DOCTOR EMAIL t/TAG");
         commandSyntaxMap.put("clear", "clear");
         commandSyntaxMap.put("delete", "delete INDEX");
         commandSyntaxMap.put("edit", "edit INDEX [n/NAME] [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] "
```
Comment (Johnwz123) [inline src/main/java/seedu/address/ui/CommandBox.java:44]: The edit syntax needs to be updated also.

**Review by Johnwz123 — CHANGES_REQUESTED** [review]

**Review by Johnwz123 — APPROVED** [review]
LGTM. Thanks!
